server:
  port: 9999
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB